services:
  - type: web
    name: vanishink-backend
    env: java
    plan: free
    buildCommand: "./mvnw clean install -DskipTests" 
    startCommand: "java -jar target/*.jar" 
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromSecret: SPRING_DATASOURCE_URL
      - key: SPRING_DATASOURCE_USERNAME
        fromSecret: SPRING_DATASOURCE_USERNAME
      - key: SPRING_DATASOURCE_PASSWORD
        fromSecret: SPRING_DATASOURCE_PASSWORD
      - key: CLOUDINARY_CLOUD_NAME
        fromSecret: CLOUDINARY_CLOUD_NAME
      - key: CLOUDINARY_API_KEY
        fromSecret: CLOUDINARY_API_KEY
      - key: CLOUDINARY_API_SECRET
        fromSecret: CLOUDINARY_API_SECRET